### PR TITLE
Fix caravan error spam

### PR DESCRIPTION
**Pull request by rtxyd**
This time I finally did it, this should work with no issue,
So the problem is we missed pawnGroupMakers, this is the culprit of why our caravan don't have a “trader headname” pawn as usual.
And I add all of them so it should have more compatibility. I am not good at coding, so I apologize about last hasty pull request which lacks of testing.
Catch with visual studio: 

M GDUB2ZAU$ZWK 8U%Q551O

### CODE REVIEW

**Comment by rtxyd** [comment]
waite a minute, another error cause not always alien pawns

**Comment by emipa606** [comment]
no problem, just comment when you are ready

**Comment by rtxyd** [comment]
A mod called "Milira race" still has small chance to generate human with its backstory (no error). And this comit should be no problem to function with moded caravan. As for the issue above I am trying to find a way to avoid it. 
PS: this is my first time to look into rimworld's code mechanism, so this issue may be out of my current reach.

**Comment by emipa606** [comment]
Nice work, should be published in 
7fcb49c

**Pull request merged**
